"""refactor_relation_produto_promocao

Revision ID: 0e416e331879
Revises: a1a548699c15
Create Date: 2024-06-14 14:06:38.881903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e416e331879'
down_revision: Union[str, None] = 'a1a548699c15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mercado_produto', sa.Column('promocao_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'mercado_produto', 'mercado_promocao', ['promocao_id'], ['id'])
    op.drop_column('mercado_promocao', 'produto')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mercado_promocao', sa.Column('produto', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'mercado_produto', type_='foreignkey')
    op.drop_column('mercado_produto', 'promocao_id')
    # ### end Alembic commands ###
