"""add_descricao_promocao

Revision ID: 30d05c3c8db9
Revises: 0e416e331879
Create Date: 2024-06-14 15:36:20.986539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30d05c3c8db9'
down_revision: Union[str, None] = '0e416e331879'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mercado_promocao', sa.Column('descricao', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mercado_promocao', 'descricao')
    # ### end Alembic commands ###
