"""add_foto_produto

Revision ID: 41e3f4483c60
Revises: 90f7fe03a978
Create Date: 2024-06-29 02:20:24.906050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41e3f4483c60'
down_revision: Union[str, None] = '90f7fe03a978'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mercado_produto', sa.Column('url_foto', sa.String(length=255), nullable=True))
    op.drop_column('mercado_produto', 'imagem')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mercado_produto', sa.Column('imagem', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('mercado_produto', 'url_foto')
    # ### end Alembic commands ###
