"""15_erp_conexao

Revision ID: 57e6585a9623
Revises: b6c270e1e861
Create Date: 2024-05-12 18:36:21.368731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57e6585a9623'
down_revision: Union[str, None] = 'ba67172b1256'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_mercados',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mercado_id', sa.UUID(), nullable=True),
    sa.Column('url_base', sa.String(length=255), nullable=True),
    sa.Column('porta', sa.Integer(), nullable=True),
    sa.Column('empresa_erp', sa.Enum('MAXDATA', name='tipoempresaerp'), nullable=True),
    sa.Column('terminal', sa.String(length=255), nullable=True),
    sa.Column('emp_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['mercado_id'], ['mercado_mercado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mercado_produto_promocao_erp', sa.Column('descricao', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_table('api_mercados')
    # ### end Alembic commands ###
