"""16_models_curtidas

Revision ID: 6622070a1f10
Revises: 57e6585a9623
Create Date: 2024-05-19 14:12:24.468041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6622070a1f10'
down_revision: Union[str, None] = '57e6585a9623'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mercado_curtida',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('produto_id', sa.UUID(), nullable=True),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['mercado_produto.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario_usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mercado_curtida')
    # ### end Alembic commands ###
