"""add_foto_mercado

Revision ID: 90f7fe03a978
Revises: ba21f4ba921a
Create Date: 2024-06-27 11:53:30.392382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90f7fe03a978'
down_revision: Union[str, None] = 'ba21f4ba921a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mercado_mercado', sa.Column('url_foto', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mercado_mercado', 'url_foto')
    # ### end Alembic commands ###
