"""fk_mercado_promocao

Revision ID: 9fc1aa86c5e6
Revises: 35a2bed24619
Create Date: 2024-06-03 13:10:57.765086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fc1aa86c5e6'
down_revision: Union[str, None] = '35a2bed24619'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
