"""fk_mercado_promocao

Revision ID: a1a548699c15
Revises: 9fc1aa86c5e6
Create Date: 2024-06-03 13:19:14.522240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1a548699c15'
down_revision: Union[str, None] = '9fc1aa86c5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mercado_promocao', sa.Column('mercado_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'mercado_promocao', 'mercado_mercado', ['mercado_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mercado_promocao', type_='foreignkey')
    op.drop_column('mercado_promocao', 'mercado_id')
    # ### end Alembic commands ###
