"""add_campos_post

Revision ID: ba21f4ba921a
Revises: 6ecf5539148f
Create Date: 2024-06-22 20:21:01.374563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba21f4ba921a'
down_revision: Union[str, None] = '6ecf5539148f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario_postagem_promocao', sa.Column('titulo', sa.String(length=64), nullable=False))
    op.add_column('usuario_postagem_promocao', sa.Column('produto', sa.String(length=64), nullable=True))
    op.add_column('usuario_postagem_promocao', sa.Column('preco', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario_postagem_promocao', 'preco')
    op.drop_column('usuario_postagem_promocao', 'produto')
    op.drop_column('usuario_postagem_promocao', 'titulo')
    # ### end Alembic commands ###
