"""8_fix_consumidor

Revision ID: ca26d80e0aca
Revises: 28b7b500ef27
Create Date: 2024-04-22 09:10:26.665849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca26d80e0aca'
down_revision: Union[str, None] = '28b7b500ef27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario_consumidor', sa.Column('id_usuario', sa.UUID(), nullable=False))
    op.drop_constraint('usuario_consumidor_id_fkey', 'usuario_consumidor', type_='foreignkey')
    op.create_foreign_key(None, 'usuario_consumidor', 'usuario_usuario', ['id_usuario'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario_consumidor', type_='foreignkey')
    op.create_foreign_key('usuario_consumidor_id_fkey', 'usuario_consumidor', 'usuario_usuario', ['id'], ['id'])
    op.drop_column('usuario_consumidor', 'id_usuario')
    # ### end Alembic commands ###
