"""initial_models_produto_mercado

Revision ID: 3fec810727f3
Revises: 
Create Date: 2024-04-25 09:44:14.258137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_storages


# revision identifiers, used by Alembic.
revision: str = '3fec810727f3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

storage_logo = fastapi_storages.FileSystemStorage(path="./media/logo")
storage = fastapi_storages.FileSystemStorage(path="./media/produtos")

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mercado_mercado',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('razao_social', sa.String(length=30), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=55), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('logo', fastapi_storages.integrations.sqlalchemy.ImageType(storage=storage_logo), nullable=True),
    sa.Column('telefone', sa.BigInteger(), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('estado', sa.String(length=255), nullable=False),
    sa.Column('cidade', sa.String(length=255), nullable=False),
    sa.Column('bairro', sa.String(length=255), nullable=False),
    sa.Column('endereco', sa.String(length=255), nullable=False),
    sa.Column('numero_endereco', sa.Integer(), nullable=False),
    sa.Column('complemento', sa.String(length=255), nullable=True),
    sa.Column('nome_responsavel', sa.String(length=255), nullable=False),
    sa.Column('cpf_responsavel', sa.String(length=11), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('mercado_produto',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mercado_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('marca', sa.String(length=255), nullable=True),
    sa.Column('data_validade', sa.DateTime(), nullable=True),
    sa.Column('ncm_produto', sa.String(length=10), nullable=True),
    sa.Column('gtin_produto', sa.String(length=14), nullable=True),
    sa.Column('mpn_produto', sa.String(length=30), nullable=True),
    sa.Column('id_produto_erp', sa.String(), nullable=True),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('preco', sa.Float(), nullable=True),
    sa.Column('preco_promocional', sa.Float(), nullable=True),
    sa.Column('imagem', fastapi_storages.integrations.sqlalchemy.ImageType(storage=storage), nullable=True),
    sa.Column('codigo_produto', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['mercado_id'], ['mercado_mercado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mercado_produto')
    op.drop_table('mercado_mercado')
    # ### end Alembic commands ###
