"""2_tirando_campo

Revision ID: a54e802cd4ba
Revises: 3fec810727f3
Create Date: 2024-04-25 11:22:47.282196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a54e802cd4ba'
down_revision: Union[str, None] = '3fec810727f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mercado_produto', 'id_produto_erp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mercado_produto', sa.Column('id_produto_erp', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
